server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  add-proxy-headers: true
      
spring:
  cloud:
    config:
      uri: http://localhost:8888
      