spring.profiles.active: 'local'

---

spring:
  profiles: 'local'
server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptior: TRACE
    org.hibernate.type: TRACE
    
---

spring:
  profiles: 'development'
server:
  port: 8020
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
    
