spring.profiles.active: 'cloud'

---

spring:
  profiles: 'cloud'
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leqcar/sampleConfig
server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

---

spring:
  profiles: 'development, local'
  cloud:
    config:
      server:
          # uri: D:\JONG\git\sampleConfig
        git:
          uri: file://Users/jongtenerife/git/sampleConfig
server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

